import Hero from "@/components/sections/Hero";

export default function Home() {
  return (
    <header>
      <Hero
        title="AI Generated Website"
        description="This is a website generated by AI"
      />
    </header>
  );
}
